#ifndef __PH_AP_API_H__
#define __PH_AP_API_H__
//==================================================================================================================

//Global function
extern void Vendor_Phison_Cmd();
extern void CardReader_Cmd();
extern void SW_Vol(BYTE ab_Vol_Typ, BYTE ab_Port);


//#if Hank_Test
//extern void VendorCmd_Tester2(void);
//#endif


#endif  //#ifndef __PH_AP_API_H__
